//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace norpim.UserInterface.DiagnosticsProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DiagnosticsProxy.IDiagnosticsService")]
    public interface IDiagnosticsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiagnosticsService/PingTest", ReplyAction="http://tempuri.org/IDiagnosticsService/PingTestResponse")]
        System.DateTime PingTest();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiagnosticsService/UserId", ReplyAction="http://tempuri.org/IDiagnosticsService/UserIdResponse")]
        System.Guid UserId();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiagnosticsService/Database", ReplyAction="http://tempuri.org/IDiagnosticsService/DatabaseResponse")]
        string Database();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiagnosticsService/ComputerName", ReplyAction="http://tempuri.org/IDiagnosticsService/ComputerNameResponse")]
        string ComputerName();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDiagnosticsServiceChannel : norpim.UserInterface.DiagnosticsProxy.IDiagnosticsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DiagnosticsServiceClient : System.ServiceModel.ClientBase<norpim.UserInterface.DiagnosticsProxy.IDiagnosticsService>, norpim.UserInterface.DiagnosticsProxy.IDiagnosticsService {
        
        public DiagnosticsServiceClient() {
        }
        
        public DiagnosticsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DiagnosticsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DiagnosticsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DiagnosticsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.DateTime PingTest() {
            return base.Channel.PingTest();
        }
        
        public System.Guid UserId() {
            return base.Channel.UserId();
        }
        
        public string Database() {
            return base.Channel.Database();
        }
        
        public string ComputerName() {
            return base.Channel.ComputerName();
        }
    }
}
