//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace norpim.BusinessLogicLayer.Other
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="norpim.BusinessLogicLayer.Other.IDiagnosticsService")]
    public interface IDiagnosticsService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiagnosticsService/PingTest", ReplyAction="http://tempuri.org/IDiagnosticsService/PingTestResponse")]
        System.DateTime PingTest();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiagnosticsService/PingTest", ReplyAction="http://tempuri.org/IDiagnosticsService/PingTestResponse")]
        System.Threading.Tasks.Task<System.DateTime> PingTestAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiagnosticsService/Database", ReplyAction="http://tempuri.org/IDiagnosticsService/DatabaseResponse")]
        string Database();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiagnosticsService/Database", ReplyAction="http://tempuri.org/IDiagnosticsService/DatabaseResponse")]
        System.Threading.Tasks.Task<string> DatabaseAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiagnosticsService/ComputerName", ReplyAction="http://tempuri.org/IDiagnosticsService/ComputerNameResponse")]
        string ComputerName();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiagnosticsService/ComputerName", ReplyAction="http://tempuri.org/IDiagnosticsService/ComputerNameResponse")]
        System.Threading.Tasks.Task<string> ComputerNameAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDiagnosticsServiceChannel : norpim.BusinessLogicLayer.Other.IDiagnosticsService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DiagnosticsServiceClient : System.ServiceModel.ClientBase<norpim.BusinessLogicLayer.Other.IDiagnosticsService>, norpim.BusinessLogicLayer.Other.IDiagnosticsService
    {
        
        public DiagnosticsServiceClient()
        {
        }
        
        public DiagnosticsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public DiagnosticsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public DiagnosticsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public DiagnosticsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.DateTime PingTest()
        {
            return base.Channel.PingTest();
        }
        
        public System.Threading.Tasks.Task<System.DateTime> PingTestAsync()
        {
            return base.Channel.PingTestAsync();
        }
        
        public string Database()
        {
            return base.Channel.Database();
        }
        
        public System.Threading.Tasks.Task<string> DatabaseAsync()
        {
            return base.Channel.DatabaseAsync();
        }
        
        public string ComputerName()
        {
            return base.Channel.ComputerName();
        }
        
        public System.Threading.Tasks.Task<string> ComputerNameAsync()
        {
            return base.Channel.ComputerNameAsync();
        }
    }
}
