//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace norpim.BusinessLogicLayer.Other
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductContract", Namespace="http://schemas.datacontract.org/2004/07/norpim.BusinessLogicLayer")]
    public partial class ProductContract : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private norpim.BusinessLogicLayer.Other.CrudeProductContract ProductField;
        
        private norpim.BusinessLogicLayer.Other.CrudeProductAttributeContract[] ProductAttributeField;
        
        private norpim.BusinessLogicLayer.Other.CrudeProductDocumentationContract[] ProductDocumentationField;
        
        private norpim.BusinessLogicLayer.Other.CrudeProductIdentifierContract[] ProductIdentifierField;
        
        private norpim.BusinessLogicLayer.Other.CrudeProductImageContract[] ProductImageField;
        
        private norpim.BusinessLogicLayer.Other.CrudeProductInfoContract[] ProductInfoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public norpim.BusinessLogicLayer.Other.CrudeProductContract Product
        {
            get
            {
                return this.ProductField;
            }
            set
            {
                this.ProductField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public norpim.BusinessLogicLayer.Other.CrudeProductAttributeContract[] ProductAttribute
        {
            get
            {
                return this.ProductAttributeField;
            }
            set
            {
                this.ProductAttributeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public norpim.BusinessLogicLayer.Other.CrudeProductDocumentationContract[] ProductDocumentation
        {
            get
            {
                return this.ProductDocumentationField;
            }
            set
            {
                this.ProductDocumentationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public norpim.BusinessLogicLayer.Other.CrudeProductIdentifierContract[] ProductIdentifier
        {
            get
            {
                return this.ProductIdentifierField;
            }
            set
            {
                this.ProductIdentifierField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public norpim.BusinessLogicLayer.Other.CrudeProductImageContract[] ProductImage
        {
            get
            {
                return this.ProductImageField;
            }
            set
            {
                this.ProductImageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public norpim.BusinessLogicLayer.Other.CrudeProductInfoContract[] ProductInfo
        {
            get
            {
                return this.ProductInfoField;
            }
            set
            {
                this.ProductInfoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CrudeProductContract", Namespace="http://schemas.datacontract.org/2004/07/norpim.BusinessLogicLayer")]
    public partial class CrudeProductContract : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime DateTimeField;
        
        private System.Guid ProductBecameIdField;
        
        private System.Guid ProductIdField;
        
        private string ProductNameField;
        
        private string StateRcdField;
        
        private System.Guid UserIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateTime
        {
            get
            {
                return this.DateTimeField;
            }
            set
            {
                this.DateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ProductBecameId
        {
            get
            {
                return this.ProductBecameIdField;
            }
            set
            {
                this.ProductBecameIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ProductId
        {
            get
            {
                return this.ProductIdField;
            }
            set
            {
                this.ProductIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName
        {
            get
            {
                return this.ProductNameField;
            }
            set
            {
                this.ProductNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StateRcd
        {
            get
            {
                return this.StateRcdField;
            }
            set
            {
                this.StateRcdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CrudeProductAttributeContract", Namespace="http://schemas.datacontract.org/2004/07/norpim.BusinessLogicLayer")]
    public partial class CrudeProductAttributeContract : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime DateTimeField;
        
        private System.Guid ProductAttributeIdField;
        
        private string ProductAttributeRcdField;
        
        private string ProductAttributeUnitRcdField;
        
        private System.Guid ProductIdField;
        
        private System.Guid UserIdField;
        
        private string ValueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateTime
        {
            get
            {
                return this.DateTimeField;
            }
            set
            {
                this.DateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ProductAttributeId
        {
            get
            {
                return this.ProductAttributeIdField;
            }
            set
            {
                this.ProductAttributeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductAttributeRcd
        {
            get
            {
                return this.ProductAttributeRcdField;
            }
            set
            {
                this.ProductAttributeRcdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductAttributeUnitRcd
        {
            get
            {
                return this.ProductAttributeUnitRcdField;
            }
            set
            {
                this.ProductAttributeUnitRcdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ProductId
        {
            get
            {
                return this.ProductIdField;
            }
            set
            {
                this.ProductIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CrudeProductDocumentationContract", Namespace="http://schemas.datacontract.org/2004/07/norpim.BusinessLogicLayer")]
    public partial class CrudeProductDocumentationContract : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime DateTimeField;
        
        private string DocumentationField;
        
        private System.Guid ProductDocumentationIdField;
        
        private string ProductDocumentationTypeRcdField;
        
        private System.Guid ProductIdField;
        
        private System.Guid UserIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateTime
        {
            get
            {
                return this.DateTimeField;
            }
            set
            {
                this.DateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Documentation
        {
            get
            {
                return this.DocumentationField;
            }
            set
            {
                this.DocumentationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ProductDocumentationId
        {
            get
            {
                return this.ProductDocumentationIdField;
            }
            set
            {
                this.ProductDocumentationIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductDocumentationTypeRcd
        {
            get
            {
                return this.ProductDocumentationTypeRcdField;
            }
            set
            {
                this.ProductDocumentationTypeRcdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ProductId
        {
            get
            {
                return this.ProductIdField;
            }
            set
            {
                this.ProductIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CrudeProductIdentifierContract", Namespace="http://schemas.datacontract.org/2004/07/norpim.BusinessLogicLayer")]
    public partial class CrudeProductIdentifierContract : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime DateTimeField;
        
        private string IdentifierField;
        
        private System.Guid ProductIdField;
        
        private System.Guid ProductIdentifierIdField;
        
        private string ProductIdentifierRcdField;
        
        private System.Guid UserIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateTime
        {
            get
            {
                return this.DateTimeField;
            }
            set
            {
                this.DateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identifier
        {
            get
            {
                return this.IdentifierField;
            }
            set
            {
                this.IdentifierField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ProductId
        {
            get
            {
                return this.ProductIdField;
            }
            set
            {
                this.ProductIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ProductIdentifierId
        {
            get
            {
                return this.ProductIdentifierIdField;
            }
            set
            {
                this.ProductIdentifierIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductIdentifierRcd
        {
            get
            {
                return this.ProductIdentifierRcdField;
            }
            set
            {
                this.ProductIdentifierRcdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CrudeProductImageContract", Namespace="http://schemas.datacontract.org/2004/07/norpim.BusinessLogicLayer")]
    public partial class CrudeProductImageContract : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime DateTimeField;
        
        private byte[] ImageField;
        
        private string ImageFileNameField;
        
        private System.Guid ProductIdField;
        
        private System.Guid ProductImageIdField;
        
        private string ProductImageTypeRcdField;
        
        private System.Guid UserIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateTime
        {
            get
            {
                return this.DateTimeField;
            }
            set
            {
                this.DateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Image
        {
            get
            {
                return this.ImageField;
            }
            set
            {
                this.ImageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageFileName
        {
            get
            {
                return this.ImageFileNameField;
            }
            set
            {
                this.ImageFileNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ProductId
        {
            get
            {
                return this.ProductIdField;
            }
            set
            {
                this.ProductIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ProductImageId
        {
            get
            {
                return this.ProductImageIdField;
            }
            set
            {
                this.ProductImageIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductImageTypeRcd
        {
            get
            {
                return this.ProductImageTypeRcdField;
            }
            set
            {
                this.ProductImageTypeRcdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CrudeProductInfoContract", Namespace="http://schemas.datacontract.org/2004/07/norpim.BusinessLogicLayer")]
    public partial class CrudeProductInfoContract : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime DateTimeField;
        
        private System.Guid ProductIdField;
        
        private System.Guid ProductInfoIdField;
        
        private string ProductInfoRcdField;
        
        private string ProductInfoValueField;
        
        private System.Guid UserIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateTime
        {
            get
            {
                return this.DateTimeField;
            }
            set
            {
                this.DateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ProductId
        {
            get
            {
                return this.ProductIdField;
            }
            set
            {
                this.ProductIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ProductInfoId
        {
            get
            {
                return this.ProductInfoIdField;
            }
            set
            {
                this.ProductInfoIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductInfoRcd
        {
            get
            {
                return this.ProductInfoRcdField;
            }
            set
            {
                this.ProductInfoRcdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductInfoValue
        {
            get
            {
                return this.ProductInfoValueField;
            }
            set
            {
                this.ProductInfoValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductHistoryContract", Namespace="http://schemas.datacontract.org/2004/07/norpim.BusinessLogicLayer")]
    public partial class ProductHistoryContract : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime DateTimeField;
        
        private System.Guid ProductBecameIdField;
        
        private System.Guid ProductIdField;
        
        private string ProductNameField;
        
        private string StateNameField;
        
        private string UserNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateTime
        {
            get
            {
                return this.DateTimeField;
            }
            set
            {
                this.DateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ProductBecameId
        {
            get
            {
                return this.ProductBecameIdField;
            }
            set
            {
                this.ProductBecameIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ProductId
        {
            get
            {
                return this.ProductIdField;
            }
            set
            {
                this.ProductIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName
        {
            get
            {
                return this.ProductNameField;
            }
            set
            {
                this.ProductNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StateName
        {
            get
            {
                return this.StateNameField;
            }
            set
            {
                this.StateNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="norpim.BusinessLogicLayer.Other.IProductService")]
    public interface IProductService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/ProductGetCompleteById", ReplyAction="http://tempuri.org/IProductService/ProductGetCompleteByIdResponse")]
        norpim.BusinessLogicLayer.Other.ProductContract ProductGetCompleteById(System.Guid productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/ProductGetCompleteById", ReplyAction="http://tempuri.org/IProductService/ProductGetCompleteByIdResponse")]
        System.Threading.Tasks.Task<norpim.BusinessLogicLayer.Other.ProductContract> ProductGetCompleteByIdAsync(System.Guid productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/ProductSaveCompleteById", ReplyAction="http://tempuri.org/IProductService/ProductSaveCompleteByIdResponse")]
        void ProductSaveCompleteById(norpim.BusinessLogicLayer.Other.ProductContract contract, System.Guid userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/ProductSaveCompleteById", ReplyAction="http://tempuri.org/IProductService/ProductSaveCompleteByIdResponse")]
        System.Threading.Tasks.Task ProductSaveCompleteByIdAsync(norpim.BusinessLogicLayer.Other.ProductContract contract, System.Guid userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/ProductAdd", ReplyAction="http://tempuri.org/IProductService/ProductAddResponse")]
        System.Guid ProductAdd(System.Guid productCategoryId, string productName, System.Guid userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/ProductAdd", ReplyAction="http://tempuri.org/IProductService/ProductAddResponse")]
        System.Threading.Tasks.Task<System.Guid> ProductAddAsync(System.Guid productCategoryId, string productName, System.Guid userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/ProductHistory", ReplyAction="http://tempuri.org/IProductService/ProductHistoryResponse")]
        norpim.BusinessLogicLayer.Other.ProductHistoryContract[] ProductHistory(System.Guid productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/ProductHistory", ReplyAction="http://tempuri.org/IProductService/ProductHistoryResponse")]
        System.Threading.Tasks.Task<norpim.BusinessLogicLayer.Other.ProductHistoryContract[]> ProductHistoryAsync(System.Guid productId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductServiceChannel : norpim.BusinessLogicLayer.Other.IProductService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductServiceClient : System.ServiceModel.ClientBase<norpim.BusinessLogicLayer.Other.IProductService>, norpim.BusinessLogicLayer.Other.IProductService
    {
        
        public ProductServiceClient()
        {
        }
        
        public ProductServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public ProductServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ProductServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ProductServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public norpim.BusinessLogicLayer.Other.ProductContract ProductGetCompleteById(System.Guid productId)
        {
            return base.Channel.ProductGetCompleteById(productId);
        }
        
        public System.Threading.Tasks.Task<norpim.BusinessLogicLayer.Other.ProductContract> ProductGetCompleteByIdAsync(System.Guid productId)
        {
            return base.Channel.ProductGetCompleteByIdAsync(productId);
        }
        
        public void ProductSaveCompleteById(norpim.BusinessLogicLayer.Other.ProductContract contract, System.Guid userId)
        {
            base.Channel.ProductSaveCompleteById(contract, userId);
        }
        
        public System.Threading.Tasks.Task ProductSaveCompleteByIdAsync(norpim.BusinessLogicLayer.Other.ProductContract contract, System.Guid userId)
        {
            return base.Channel.ProductSaveCompleteByIdAsync(contract, userId);
        }
        
        public System.Guid ProductAdd(System.Guid productCategoryId, string productName, System.Guid userId)
        {
            return base.Channel.ProductAdd(productCategoryId, productName, userId);
        }
        
        public System.Threading.Tasks.Task<System.Guid> ProductAddAsync(System.Guid productCategoryId, string productName, System.Guid userId)
        {
            return base.Channel.ProductAddAsync(productCategoryId, productName, userId);
        }
        
        public norpim.BusinessLogicLayer.Other.ProductHistoryContract[] ProductHistory(System.Guid productId)
        {
            return base.Channel.ProductHistory(productId);
        }
        
        public System.Threading.Tasks.Task<norpim.BusinessLogicLayer.Other.ProductHistoryContract[]> ProductHistoryAsync(System.Guid productId)
        {
            return base.Channel.ProductHistoryAsync(productId);
        }
    }
}
