//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace norpim.BusinessLogicLayer.Other
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductCategoryContract", Namespace="http://schemas.datacontract.org/2004/07/norpim.BusinessLogicLayer")]
    public partial class ProductCategoryContract : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private norpim.BusinessLogicLayer.Other.CrudeProductCategoryContract ProductCategoryField;
        
        private norpim.BusinessLogicLayer.Other.CrudeProductCategoryDocumentationContract[] ProductCategoryDocumentationField;
        
        private norpim.BusinessLogicLayer.Other.CrudeProductCategoryImageContract[] ProductCategoryImageField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public norpim.BusinessLogicLayer.Other.CrudeProductCategoryContract ProductCategory
        {
            get
            {
                return this.ProductCategoryField;
            }
            set
            {
                this.ProductCategoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public norpim.BusinessLogicLayer.Other.CrudeProductCategoryDocumentationContract[] ProductCategoryDocumentation
        {
            get
            {
                return this.ProductCategoryDocumentationField;
            }
            set
            {
                this.ProductCategoryDocumentationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public norpim.BusinessLogicLayer.Other.CrudeProductCategoryImageContract[] ProductCategoryImage
        {
            get
            {
                return this.ProductCategoryImageField;
            }
            set
            {
                this.ProductCategoryImageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CrudeProductCategoryContract", Namespace="http://schemas.datacontract.org/2004/07/norpim.BusinessLogicLayer")]
    public partial class CrudeProductCategoryContract : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime DateTimeField;
        
        private System.Guid ProductCategoryBecameIdField;
        
        private string ProductCategoryCodeField;
        
        private System.Guid ProductCategoryIdField;
        
        private string ProductCategoryNameField;
        
        private System.Guid ProductCategoryParentIdField;
        
        private int ProductCategoryPositionField;
        
        private string StateRcdField;
        
        private System.Guid UserIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateTime
        {
            get
            {
                return this.DateTimeField;
            }
            set
            {
                this.DateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ProductCategoryBecameId
        {
            get
            {
                return this.ProductCategoryBecameIdField;
            }
            set
            {
                this.ProductCategoryBecameIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductCategoryCode
        {
            get
            {
                return this.ProductCategoryCodeField;
            }
            set
            {
                this.ProductCategoryCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ProductCategoryId
        {
            get
            {
                return this.ProductCategoryIdField;
            }
            set
            {
                this.ProductCategoryIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductCategoryName
        {
            get
            {
                return this.ProductCategoryNameField;
            }
            set
            {
                this.ProductCategoryNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ProductCategoryParentId
        {
            get
            {
                return this.ProductCategoryParentIdField;
            }
            set
            {
                this.ProductCategoryParentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductCategoryPosition
        {
            get
            {
                return this.ProductCategoryPositionField;
            }
            set
            {
                this.ProductCategoryPositionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StateRcd
        {
            get
            {
                return this.StateRcdField;
            }
            set
            {
                this.StateRcdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CrudeProductCategoryDocumentationContract", Namespace="http://schemas.datacontract.org/2004/07/norpim.BusinessLogicLayer")]
    public partial class CrudeProductCategoryDocumentationContract : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime DateTimeField;
        
        private string DocumentationField;
        
        private System.Guid ProductCategoryDocumentationIdField;
        
        private string ProductCategoryDocumentationTypeRcdField;
        
        private System.Guid ProductCategoryIdField;
        
        private System.Guid UserIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateTime
        {
            get
            {
                return this.DateTimeField;
            }
            set
            {
                this.DateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Documentation
        {
            get
            {
                return this.DocumentationField;
            }
            set
            {
                this.DocumentationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ProductCategoryDocumentationId
        {
            get
            {
                return this.ProductCategoryDocumentationIdField;
            }
            set
            {
                this.ProductCategoryDocumentationIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductCategoryDocumentationTypeRcd
        {
            get
            {
                return this.ProductCategoryDocumentationTypeRcdField;
            }
            set
            {
                this.ProductCategoryDocumentationTypeRcdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ProductCategoryId
        {
            get
            {
                return this.ProductCategoryIdField;
            }
            set
            {
                this.ProductCategoryIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CrudeProductCategoryImageContract", Namespace="http://schemas.datacontract.org/2004/07/norpim.BusinessLogicLayer")]
    public partial class CrudeProductCategoryImageContract : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime DateTimeField;
        
        private byte[] ImageField;
        
        private System.Guid ProductCategoryIdField;
        
        private System.Guid ProductCategoryImageIdField;
        
        private string ProductCategoryImageTypeRcdField;
        
        private System.Guid UserIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateTime
        {
            get
            {
                return this.DateTimeField;
            }
            set
            {
                this.DateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Image
        {
            get
            {
                return this.ImageField;
            }
            set
            {
                this.ImageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ProductCategoryId
        {
            get
            {
                return this.ProductCategoryIdField;
            }
            set
            {
                this.ProductCategoryIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ProductCategoryImageId
        {
            get
            {
                return this.ProductCategoryImageIdField;
            }
            set
            {
                this.ProductCategoryImageIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductCategoryImageTypeRcd
        {
            get
            {
                return this.ProductCategoryImageTypeRcdField;
            }
            set
            {
                this.ProductCategoryImageTypeRcdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="norpim.BusinessLogicLayer.Other.IProductCategoryService")]
    public interface IProductCategoryService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductCategoryService/CleanSlate", ReplyAction="http://tempuri.org/IProductCategoryService/CleanSlateResponse")]
        void CleanSlate(System.Guid userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductCategoryService/CleanSlate", ReplyAction="http://tempuri.org/IProductCategoryService/CleanSlateResponse")]
        System.Threading.Tasks.Task CleanSlateAsync(System.Guid userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductCategoryService/ProductCategoryAdd", ReplyAction="http://tempuri.org/IProductCategoryService/ProductCategoryAddResponse")]
        System.Guid ProductCategoryAdd(string productCategoryCode, string productCategoryName, System.Guid productCategoryParentId, int productCategoryPosition, System.Guid userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductCategoryService/ProductCategoryAdd", ReplyAction="http://tempuri.org/IProductCategoryService/ProductCategoryAddResponse")]
        System.Threading.Tasks.Task<System.Guid> ProductCategoryAddAsync(string productCategoryCode, string productCategoryName, System.Guid productCategoryParentId, int productCategoryPosition, System.Guid userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductCategoryService/ProductCategoryGetCompleteById", ReplyAction="http://tempuri.org/IProductCategoryService/ProductCategoryGetCompleteByIdResponse" +
            "")]
        norpim.BusinessLogicLayer.Other.ProductCategoryContract ProductCategoryGetCompleteById(System.Guid productCategoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductCategoryService/ProductCategoryGetCompleteById", ReplyAction="http://tempuri.org/IProductCategoryService/ProductCategoryGetCompleteByIdResponse" +
            "")]
        System.Threading.Tasks.Task<norpim.BusinessLogicLayer.Other.ProductCategoryContract> ProductCategoryGetCompleteByIdAsync(System.Guid productCategoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductCategoryService/PositionDown", ReplyAction="http://tempuri.org/IProductCategoryService/PositionDownResponse")]
        long PositionDown(System.Guid productCategoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductCategoryService/PositionDown", ReplyAction="http://tempuri.org/IProductCategoryService/PositionDownResponse")]
        System.Threading.Tasks.Task<long> PositionDownAsync(System.Guid productCategoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductCategoryService/PositionUp", ReplyAction="http://tempuri.org/IProductCategoryService/PositionUpResponse")]
        long PositionUp(System.Guid productCategoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductCategoryService/PositionUp", ReplyAction="http://tempuri.org/IProductCategoryService/PositionUpResponse")]
        System.Threading.Tasks.Task<long> PositionUpAsync(System.Guid productCategoryId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductCategoryServiceChannel : norpim.BusinessLogicLayer.Other.IProductCategoryService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductCategoryServiceClient : System.ServiceModel.ClientBase<norpim.BusinessLogicLayer.Other.IProductCategoryService>, norpim.BusinessLogicLayer.Other.IProductCategoryService
    {
        
        public ProductCategoryServiceClient()
        {
        }
        
        public ProductCategoryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public ProductCategoryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ProductCategoryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ProductCategoryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public void CleanSlate(System.Guid userId)
        {
            base.Channel.CleanSlate(userId);
        }
        
        public System.Threading.Tasks.Task CleanSlateAsync(System.Guid userId)
        {
            return base.Channel.CleanSlateAsync(userId);
        }
        
        public System.Guid ProductCategoryAdd(string productCategoryCode, string productCategoryName, System.Guid productCategoryParentId, int productCategoryPosition, System.Guid userId)
        {
            return base.Channel.ProductCategoryAdd(productCategoryCode, productCategoryName, productCategoryParentId, productCategoryPosition, userId);
        }
        
        public System.Threading.Tasks.Task<System.Guid> ProductCategoryAddAsync(string productCategoryCode, string productCategoryName, System.Guid productCategoryParentId, int productCategoryPosition, System.Guid userId)
        {
            return base.Channel.ProductCategoryAddAsync(productCategoryCode, productCategoryName, productCategoryParentId, productCategoryPosition, userId);
        }
        
        public norpim.BusinessLogicLayer.Other.ProductCategoryContract ProductCategoryGetCompleteById(System.Guid productCategoryId)
        {
            return base.Channel.ProductCategoryGetCompleteById(productCategoryId);
        }
        
        public System.Threading.Tasks.Task<norpim.BusinessLogicLayer.Other.ProductCategoryContract> ProductCategoryGetCompleteByIdAsync(System.Guid productCategoryId)
        {
            return base.Channel.ProductCategoryGetCompleteByIdAsync(productCategoryId);
        }
        
        public long PositionDown(System.Guid productCategoryId)
        {
            return base.Channel.PositionDown(productCategoryId);
        }
        
        public System.Threading.Tasks.Task<long> PositionDownAsync(System.Guid productCategoryId)
        {
            return base.Channel.PositionDownAsync(productCategoryId);
        }
        
        public long PositionUp(System.Guid productCategoryId)
        {
            return base.Channel.PositionUp(productCategoryId);
        }
        
        public System.Threading.Tasks.Task<long> PositionUpAsync(System.Guid productCategoryId)
        {
            return base.Channel.PositionUpAsync(productCategoryId);
        }
    }
}
