//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace norpim.UserInterface.ProductProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductContract", Namespace="http://schemas.datacontract.org/2004/07/norpim.BusinessLogicLayer")]
    [System.SerializableAttribute()]
    public partial class ProductContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private norpim.UserInterface.ProductProxy.CrudeProductContract ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private norpim.UserInterface.ProductProxy.CrudeProductAttributeContract[] ProductAttributeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private norpim.UserInterface.ProductProxy.CrudeProductDocumentationContract[] ProductDocumentationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private norpim.UserInterface.ProductProxy.CrudeProductIdentifierContract[] ProductIdentifierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private norpim.UserInterface.ProductProxy.CrudeProductImageContract[] ProductImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private norpim.UserInterface.ProductProxy.CrudeProductInfoContract[] ProductInfoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public norpim.UserInterface.ProductProxy.CrudeProductContract Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public norpim.UserInterface.ProductProxy.CrudeProductAttributeContract[] ProductAttribute {
            get {
                return this.ProductAttributeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductAttributeField, value) != true)) {
                    this.ProductAttributeField = value;
                    this.RaisePropertyChanged("ProductAttribute");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public norpim.UserInterface.ProductProxy.CrudeProductDocumentationContract[] ProductDocumentation {
            get {
                return this.ProductDocumentationField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductDocumentationField, value) != true)) {
                    this.ProductDocumentationField = value;
                    this.RaisePropertyChanged("ProductDocumentation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public norpim.UserInterface.ProductProxy.CrudeProductIdentifierContract[] ProductIdentifier {
            get {
                return this.ProductIdentifierField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductIdentifierField, value) != true)) {
                    this.ProductIdentifierField = value;
                    this.RaisePropertyChanged("ProductIdentifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public norpim.UserInterface.ProductProxy.CrudeProductImageContract[] ProductImage {
            get {
                return this.ProductImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductImageField, value) != true)) {
                    this.ProductImageField = value;
                    this.RaisePropertyChanged("ProductImage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public norpim.UserInterface.ProductProxy.CrudeProductInfoContract[] ProductInfo {
            get {
                return this.ProductInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductInfoField, value) != true)) {
                    this.ProductInfoField = value;
                    this.RaisePropertyChanged("ProductInfo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CrudeProductContract", Namespace="http://schemas.datacontract.org/2004/07/norpim.BusinessLogicLayer")]
    [System.SerializableAttribute()]
    public partial class CrudeProductContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ProductBecameIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateRcdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid SystemOwnerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateTime {
            get {
                return this.DateTimeField;
            }
            set {
                if ((this.DateTimeField.Equals(value) != true)) {
                    this.DateTimeField = value;
                    this.RaisePropertyChanged("DateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ProductBecameId {
            get {
                return this.ProductBecameIdField;
            }
            set {
                if ((this.ProductBecameIdField.Equals(value) != true)) {
                    this.ProductBecameIdField = value;
                    this.RaisePropertyChanged("ProductBecameId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StateRcd {
            get {
                return this.StateRcdField;
            }
            set {
                if ((object.ReferenceEquals(this.StateRcdField, value) != true)) {
                    this.StateRcdField = value;
                    this.RaisePropertyChanged("StateRcd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid SystemOwnerId {
            get {
                return this.SystemOwnerIdField;
            }
            set {
                if ((this.SystemOwnerIdField.Equals(value) != true)) {
                    this.SystemOwnerIdField = value;
                    this.RaisePropertyChanged("SystemOwnerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CrudeProductAttributeContract", Namespace="http://schemas.datacontract.org/2004/07/norpim.BusinessLogicLayer")]
    [System.SerializableAttribute()]
    public partial class CrudeProductAttributeContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ProductAttributeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductAttributeRcdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductAttributeUnitRcdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateTime {
            get {
                return this.DateTimeField;
            }
            set {
                if ((this.DateTimeField.Equals(value) != true)) {
                    this.DateTimeField = value;
                    this.RaisePropertyChanged("DateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ProductAttributeId {
            get {
                return this.ProductAttributeIdField;
            }
            set {
                if ((this.ProductAttributeIdField.Equals(value) != true)) {
                    this.ProductAttributeIdField = value;
                    this.RaisePropertyChanged("ProductAttributeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductAttributeRcd {
            get {
                return this.ProductAttributeRcdField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductAttributeRcdField, value) != true)) {
                    this.ProductAttributeRcdField = value;
                    this.RaisePropertyChanged("ProductAttributeRcd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductAttributeUnitRcd {
            get {
                return this.ProductAttributeUnitRcdField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductAttributeUnitRcdField, value) != true)) {
                    this.ProductAttributeUnitRcdField = value;
                    this.RaisePropertyChanged("ProductAttributeUnitRcd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CrudeProductDocumentationContract", Namespace="http://schemas.datacontract.org/2004/07/norpim.BusinessLogicLayer")]
    [System.SerializableAttribute()]
    public partial class CrudeProductDocumentationContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ProductDocumentationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductDocumentationTypeRcdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateTime {
            get {
                return this.DateTimeField;
            }
            set {
                if ((this.DateTimeField.Equals(value) != true)) {
                    this.DateTimeField = value;
                    this.RaisePropertyChanged("DateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Documentation {
            get {
                return this.DocumentationField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentationField, value) != true)) {
                    this.DocumentationField = value;
                    this.RaisePropertyChanged("Documentation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ProductDocumentationId {
            get {
                return this.ProductDocumentationIdField;
            }
            set {
                if ((this.ProductDocumentationIdField.Equals(value) != true)) {
                    this.ProductDocumentationIdField = value;
                    this.RaisePropertyChanged("ProductDocumentationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductDocumentationTypeRcd {
            get {
                return this.ProductDocumentationTypeRcdField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductDocumentationTypeRcdField, value) != true)) {
                    this.ProductDocumentationTypeRcdField = value;
                    this.RaisePropertyChanged("ProductDocumentationTypeRcd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CrudeProductIdentifierContract", Namespace="http://schemas.datacontract.org/2004/07/norpim.BusinessLogicLayer")]
    [System.SerializableAttribute()]
    public partial class CrudeProductIdentifierContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentifierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ProductIdentifierIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductIdentifierRcdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateTime {
            get {
                return this.DateTimeField;
            }
            set {
                if ((this.DateTimeField.Equals(value) != true)) {
                    this.DateTimeField = value;
                    this.RaisePropertyChanged("DateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identifier {
            get {
                return this.IdentifierField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentifierField, value) != true)) {
                    this.IdentifierField = value;
                    this.RaisePropertyChanged("Identifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ProductIdentifierId {
            get {
                return this.ProductIdentifierIdField;
            }
            set {
                if ((this.ProductIdentifierIdField.Equals(value) != true)) {
                    this.ProductIdentifierIdField = value;
                    this.RaisePropertyChanged("ProductIdentifierId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductIdentifierRcd {
            get {
                return this.ProductIdentifierRcdField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductIdentifierRcdField, value) != true)) {
                    this.ProductIdentifierRcdField = value;
                    this.RaisePropertyChanged("ProductIdentifierRcd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CrudeProductImageContract", Namespace="http://schemas.datacontract.org/2004/07/norpim.BusinessLogicLayer")]
    [System.SerializableAttribute()]
    public partial class CrudeProductImageContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ProductImageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductImageTypeRcdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateTime {
            get {
                return this.DateTimeField;
            }
            set {
                if ((this.DateTimeField.Equals(value) != true)) {
                    this.DateTimeField = value;
                    this.RaisePropertyChanged("DateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ProductImageId {
            get {
                return this.ProductImageIdField;
            }
            set {
                if ((this.ProductImageIdField.Equals(value) != true)) {
                    this.ProductImageIdField = value;
                    this.RaisePropertyChanged("ProductImageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductImageTypeRcd {
            get {
                return this.ProductImageTypeRcdField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductImageTypeRcdField, value) != true)) {
                    this.ProductImageTypeRcdField = value;
                    this.RaisePropertyChanged("ProductImageTypeRcd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CrudeProductInfoContract", Namespace="http://schemas.datacontract.org/2004/07/norpim.BusinessLogicLayer")]
    [System.SerializableAttribute()]
    public partial class CrudeProductInfoContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ProductInfoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductInfoRcdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductInfoValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateTime {
            get {
                return this.DateTimeField;
            }
            set {
                if ((this.DateTimeField.Equals(value) != true)) {
                    this.DateTimeField = value;
                    this.RaisePropertyChanged("DateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ProductInfoId {
            get {
                return this.ProductInfoIdField;
            }
            set {
                if ((this.ProductInfoIdField.Equals(value) != true)) {
                    this.ProductInfoIdField = value;
                    this.RaisePropertyChanged("ProductInfoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductInfoRcd {
            get {
                return this.ProductInfoRcdField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductInfoRcdField, value) != true)) {
                    this.ProductInfoRcdField = value;
                    this.RaisePropertyChanged("ProductInfoRcd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductInfoValue {
            get {
                return this.ProductInfoValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductInfoValueField, value) != true)) {
                    this.ProductInfoValueField = value;
                    this.RaisePropertyChanged("ProductInfoValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductProxy.IProductService")]
    public interface IProductService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/ProductGetCompleteById", ReplyAction="http://tempuri.org/IProductService/ProductGetCompleteByIdResponse")]
        norpim.UserInterface.ProductProxy.ProductContract ProductGetCompleteById(System.Guid productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/ProductSaveCompleteById", ReplyAction="http://tempuri.org/IProductService/ProductSaveCompleteByIdResponse")]
        void ProductSaveCompleteById(norpim.UserInterface.ProductProxy.ProductContract contract, System.Guid userId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductServiceChannel : norpim.UserInterface.ProductProxy.IProductService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductServiceClient : System.ServiceModel.ClientBase<norpim.UserInterface.ProductProxy.IProductService>, norpim.UserInterface.ProductProxy.IProductService {
        
        public ProductServiceClient() {
        }
        
        public ProductServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public norpim.UserInterface.ProductProxy.ProductContract ProductGetCompleteById(System.Guid productId) {
            return base.Channel.ProductGetCompleteById(productId);
        }
        
        public void ProductSaveCompleteById(norpim.UserInterface.ProductProxy.ProductContract contract, System.Guid userId) {
            base.Channel.ProductSaveCompleteById(contract, userId);
        }
    }
}
