//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace norpim.UserInterface.CategoryProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductCategoryContract", Namespace="http://schemas.datacontract.org/2004/07/norpim.BusinessLogicLayer")]
    [System.SerializableAttribute()]
    public partial class ProductCategoryContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private norpim.UserInterface.CategoryProxy.CrudeProductCategoryContract ProductCategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private norpim.UserInterface.CategoryProxy.CrudeProductCategoryDocumentationContract[] ProductCategoryDocumentationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private norpim.UserInterface.CategoryProxy.CrudeProductCategoryImageContract[] ProductCategoryImageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public norpim.UserInterface.CategoryProxy.CrudeProductCategoryContract ProductCategory {
            get {
                return this.ProductCategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductCategoryField, value) != true)) {
                    this.ProductCategoryField = value;
                    this.RaisePropertyChanged("ProductCategory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public norpim.UserInterface.CategoryProxy.CrudeProductCategoryDocumentationContract[] ProductCategoryDocumentation {
            get {
                return this.ProductCategoryDocumentationField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductCategoryDocumentationField, value) != true)) {
                    this.ProductCategoryDocumentationField = value;
                    this.RaisePropertyChanged("ProductCategoryDocumentation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public norpim.UserInterface.CategoryProxy.CrudeProductCategoryImageContract[] ProductCategoryImage {
            get {
                return this.ProductCategoryImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductCategoryImageField, value) != true)) {
                    this.ProductCategoryImageField = value;
                    this.RaisePropertyChanged("ProductCategoryImage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CrudeProductCategoryContract", Namespace="http://schemas.datacontract.org/2004/07/norpim.BusinessLogicLayer")]
    [System.SerializableAttribute()]
    public partial class CrudeProductCategoryContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ProductCategoryBecameIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductCategoryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ProductCategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductCategoryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ProductCategoryParentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductCategoryPositionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateRcdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid SystemOwnerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateTime {
            get {
                return this.DateTimeField;
            }
            set {
                if ((this.DateTimeField.Equals(value) != true)) {
                    this.DateTimeField = value;
                    this.RaisePropertyChanged("DateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ProductCategoryBecameId {
            get {
                return this.ProductCategoryBecameIdField;
            }
            set {
                if ((this.ProductCategoryBecameIdField.Equals(value) != true)) {
                    this.ProductCategoryBecameIdField = value;
                    this.RaisePropertyChanged("ProductCategoryBecameId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductCategoryCode {
            get {
                return this.ProductCategoryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductCategoryCodeField, value) != true)) {
                    this.ProductCategoryCodeField = value;
                    this.RaisePropertyChanged("ProductCategoryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ProductCategoryId {
            get {
                return this.ProductCategoryIdField;
            }
            set {
                if ((this.ProductCategoryIdField.Equals(value) != true)) {
                    this.ProductCategoryIdField = value;
                    this.RaisePropertyChanged("ProductCategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductCategoryName {
            get {
                return this.ProductCategoryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductCategoryNameField, value) != true)) {
                    this.ProductCategoryNameField = value;
                    this.RaisePropertyChanged("ProductCategoryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ProductCategoryParentId {
            get {
                return this.ProductCategoryParentIdField;
            }
            set {
                if ((this.ProductCategoryParentIdField.Equals(value) != true)) {
                    this.ProductCategoryParentIdField = value;
                    this.RaisePropertyChanged("ProductCategoryParentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductCategoryPosition {
            get {
                return this.ProductCategoryPositionField;
            }
            set {
                if ((this.ProductCategoryPositionField.Equals(value) != true)) {
                    this.ProductCategoryPositionField = value;
                    this.RaisePropertyChanged("ProductCategoryPosition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StateRcd {
            get {
                return this.StateRcdField;
            }
            set {
                if ((object.ReferenceEquals(this.StateRcdField, value) != true)) {
                    this.StateRcdField = value;
                    this.RaisePropertyChanged("StateRcd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid SystemOwnerId {
            get {
                return this.SystemOwnerIdField;
            }
            set {
                if ((this.SystemOwnerIdField.Equals(value) != true)) {
                    this.SystemOwnerIdField = value;
                    this.RaisePropertyChanged("SystemOwnerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CrudeProductCategoryDocumentationContract", Namespace="http://schemas.datacontract.org/2004/07/norpim.BusinessLogicLayer")]
    [System.SerializableAttribute()]
    public partial class CrudeProductCategoryDocumentationContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ProductCategoryDocumentationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductCategoryDocumentationTypeRcdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ProductCategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateTime {
            get {
                return this.DateTimeField;
            }
            set {
                if ((this.DateTimeField.Equals(value) != true)) {
                    this.DateTimeField = value;
                    this.RaisePropertyChanged("DateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Documentation {
            get {
                return this.DocumentationField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentationField, value) != true)) {
                    this.DocumentationField = value;
                    this.RaisePropertyChanged("Documentation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ProductCategoryDocumentationId {
            get {
                return this.ProductCategoryDocumentationIdField;
            }
            set {
                if ((this.ProductCategoryDocumentationIdField.Equals(value) != true)) {
                    this.ProductCategoryDocumentationIdField = value;
                    this.RaisePropertyChanged("ProductCategoryDocumentationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductCategoryDocumentationTypeRcd {
            get {
                return this.ProductCategoryDocumentationTypeRcdField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductCategoryDocumentationTypeRcdField, value) != true)) {
                    this.ProductCategoryDocumentationTypeRcdField = value;
                    this.RaisePropertyChanged("ProductCategoryDocumentationTypeRcd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ProductCategoryId {
            get {
                return this.ProductCategoryIdField;
            }
            set {
                if ((this.ProductCategoryIdField.Equals(value) != true)) {
                    this.ProductCategoryIdField = value;
                    this.RaisePropertyChanged("ProductCategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CrudeProductCategoryImageContract", Namespace="http://schemas.datacontract.org/2004/07/norpim.BusinessLogicLayer")]
    [System.SerializableAttribute()]
    public partial class CrudeProductCategoryImageContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ProductCategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ProductCategoryImageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductCategoryImageTypeRcdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateTime {
            get {
                return this.DateTimeField;
            }
            set {
                if ((this.DateTimeField.Equals(value) != true)) {
                    this.DateTimeField = value;
                    this.RaisePropertyChanged("DateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ProductCategoryId {
            get {
                return this.ProductCategoryIdField;
            }
            set {
                if ((this.ProductCategoryIdField.Equals(value) != true)) {
                    this.ProductCategoryIdField = value;
                    this.RaisePropertyChanged("ProductCategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ProductCategoryImageId {
            get {
                return this.ProductCategoryImageIdField;
            }
            set {
                if ((this.ProductCategoryImageIdField.Equals(value) != true)) {
                    this.ProductCategoryImageIdField = value;
                    this.RaisePropertyChanged("ProductCategoryImageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductCategoryImageTypeRcd {
            get {
                return this.ProductCategoryImageTypeRcdField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductCategoryImageTypeRcdField, value) != true)) {
                    this.ProductCategoryImageTypeRcdField = value;
                    this.RaisePropertyChanged("ProductCategoryImageTypeRcd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CategoryProxy.IProductCategoryService")]
    public interface IProductCategoryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductCategoryService/CleanSlate", ReplyAction="http://tempuri.org/IProductCategoryService/CleanSlateResponse")]
        void CleanSlate(System.Guid systemOwnerId, System.Guid userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductCategoryService/ProductCategoryGetCompleteById", ReplyAction="http://tempuri.org/IProductCategoryService/ProductCategoryGetCompleteByIdResponse" +
            "")]
        norpim.UserInterface.CategoryProxy.ProductCategoryContract ProductCategoryGetCompleteById(System.Guid productCategoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductCategoryService/PositionDown", ReplyAction="http://tempuri.org/IProductCategoryService/PositionDownResponse")]
        long PositionDown(System.Guid productCategoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductCategoryService/PositionUp", ReplyAction="http://tempuri.org/IProductCategoryService/PositionUpResponse")]
        long PositionUp(System.Guid productCategoryId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductCategoryServiceChannel : norpim.UserInterface.CategoryProxy.IProductCategoryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductCategoryServiceClient : System.ServiceModel.ClientBase<norpim.UserInterface.CategoryProxy.IProductCategoryService>, norpim.UserInterface.CategoryProxy.IProductCategoryService {
        
        public ProductCategoryServiceClient() {
        }
        
        public ProductCategoryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductCategoryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductCategoryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductCategoryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CleanSlate(System.Guid systemOwnerId, System.Guid userId) {
            base.Channel.CleanSlate(systemOwnerId, userId);
        }
        
        public norpim.UserInterface.CategoryProxy.ProductCategoryContract ProductCategoryGetCompleteById(System.Guid productCategoryId) {
            return base.Channel.ProductCategoryGetCompleteById(productCategoryId);
        }
        
        public long PositionDown(System.Guid productCategoryId) {
            return base.Channel.PositionDown(productCategoryId);
        }
        
        public long PositionUp(System.Guid productCategoryId) {
            return base.Channel.PositionUp(productCategoryId);
        }
    }
}
